# Generated by Django 4.2.14 on 2024-07-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='division',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
