# Generated by Django 4.2.14 on 2024-08-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_bio_person_division_person_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='person',
            name='unique_id',
            field=models.CharField(default='DEFAULT_ID', max_length=255, unique=True),
        ),
    ]
