# Generated by Django 4.2.14 on 2024-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_person_phone_person_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('info_url', models.URLField(blank=True, max_length=500, null=True)),
                ('skill_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_type_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
